services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    pull_policy: never
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:${DB_DATADIR}
    networks:
      - wp_app
    healthcheck:
        test: ["CMD", "mariadb-admin", "ping", "-uroot", "--password=$(cat /run/secrets/db_root_password)"]
        interval: 4s
        retries: 5
        start_period: 30s
    expose:
      - 3306

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    pull_policy: never
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html/:rw
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - wp_app
    expose:
      - 9000

  nginx:
    build:
      context: ./requirements/nginx/
      args:
      - WP_DATA=${WP_DATADIR}
    image: nginx
    pull_policy: never
    restart: always
    volumes:
      - wp_data:${WP_DATADIR}:ro
    depends_on:
      wordpress:
        condition: service_started
    container_name: nginx
    networks:
      - wp_app
    ports:
      - 443:443
    expose:
      - 443

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOLUME_PATH}
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_VOLUME_PATH}

networks:
  wp_app:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

